[book]
authors = ["Matthew J. Berger"]
language = "en"
src = "src"
title = "Nightshade Game Engine"

[rust]
edition = "2024"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
mathjax-support = false
